### ISSUE TITLE
预训练权重有问题

### ISSUE THREAD

**Issue by saber131421** [Ayews/M3Net#3]
您好通过你们给的M3Net-R的权重进行评估，但是得到的结果和你们论文提供的不一致，但是你们用你们提供的预测图进行评估得到的结果是一致的，所以想问下是哪里有问题，显卡和你们用的是一样的3090

**Comment by Ayews** [comment]
感谢您的关注。我重新跑了一遍测试，得到的结果与论文提供的是一致的。我想问下您所述的不一致有多严重？根据我的经验，在不同的硬件环境下，训练与测试得到的结果均可能存在些微的差异。可能某些指标会有几个点的下滑，而另一些指标又会有几个点的上浮。如果您得到的结果与论文所述存在极大差异，以下是一些可能的原因：

1. 使用了不同的数据集加载方法。我们在dataloader中会使用imagenet上的均值与方差对输入图像进行标准化；
2. 未能成功加载预训练权重。请确保在加载预训练权重时没有使用`strict=False`这一参数。

您也可以尝试加载使用SwinTransformer的预训练权重[M3Net-S](https://pan.baidu.com/s/1ZEXR1QD2AMWQfBhxp5f8VA)[4wnw]来进行测试，或者在您的环境下以默认训练参数设置重新训练，看看结果是否仍存在较大差异。

**Comment by Ayews** [comment]
加载M3Net-S的预训练权重需修改`embed_dim`参数，通过这行代码来创建模型：
 `model = M3Net(embed_dim=512,dim=64,img_size=img_size,method='M3Net-S')`

**Comment by saber131421** [comment]
您好我经过用DUTS-TR数据集进行多次的训练基本在除DUT-O数据集上达到左右浮动的效果，基本在0.002左右浮动，但是在DUT-O的结果和您论文中提到的相差很大，大概有0.02的差距，请问你们在训练时是只使用了DUTS-TR数据集进行训练吗？






FATE
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Ayews/M3Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月24日(星期二) 下午5:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ayews/M3Net] 预训练权重有问题 (Issue #3)





 
加载M3Net-S的预训练权重需修改lembed_dim参数，通过这行代码来创建模型：
 model = M3Net(embed_dim=384,dim=64,img_size=img_size,method='M3Net-S')
